import type { RouteMatcher, UniCustomRoutesOptions } from './types'

export function withLeadingSlash(v: string): string {
  return v.startsWith('/') ? v : `/${v}`
}

export function shortenPath(pagePath: string): string {
  const segments = String(pagePath).replace(/^\/+/, '').split('/').filter(Boolean)
  const last = segments[segments.length - 1]
  if (last === 'index' && segments.length >= 2)
    return segments[segments.length - 2]
  return last
}

export function normalizeRouteMap(
  map: Record<string, string> = {},
): Record<string, string> {
  return Object.fromEntries(
    Object.entries(map).map(([from, to]) => [withLeadingSlash(from), withLeadingSlash(to)]),
  )
}

function serializeMatcher(m: RouteMatcher): string {
  // RegExp 和 Function 都有 toString，类型上 RouteMatcher 只有这三种可能
  return typeof m === 'string' ? JSON.stringify(m) : m.toString()
}

function serializeMatchers(matchers: RouteMatcher[] = []): string {
  return `[${matchers.map(serializeMatcher).join(', ')}]`
}

export function createRuntimeModule(options: UniCustomRoutesOptions = {}): string {
  const manualRoutes = normalizeRouteMap(options.manualRoutes)
  const redirects = normalizeRouteMap(options.redirects)
  const excludeCode = serializeMatchers(options.exclude)

  return `// generated by vite-plugin-uni-custom-routes
const OPTIONS = {
  exclude: ${excludeCode},
  manualRoutes: ${JSON.stringify(manualRoutes)},
  redirects: ${JSON.stringify(redirects)},
};

const NAV_APIS = ['navigateTo', 'redirectTo', 'reLaunch', 'switchTab', 'preloadPage'];

function withLeadingSlash(v) { return v.startsWith('/') ? v : '/' + v; }

function shortenPath(p) {
  const segments = String(p).replace(/^\\/+/, '').split('/').filter(Boolean);
  const last = segments[segments.length - 1];
  if (last === 'index' && segments.length >= 2) return segments[segments.length - 2];
  return last;
}

function pathCandidates(p) {
  const n = String(p).replace(/^\\/+/, '');
  if (n.startsWith('pages/')) return [n, n.slice('pages/'.length)];
  return [n, 'pages/' + n];
}

function matchesAny(matchers, p) {
  const candidates = pathCandidates(p);
  return matchers.some(m => {
    if (typeof m === 'function') return m(p);
    if (m instanceof RegExp) return candidates.some(c => m.test(c));
    const n = String(m).replace(/^\\/+/, '');
    if (n.endsWith('/**')) {
      const prefix = n.slice(0, -3);
      return candidates.some(c => c === prefix || c.startsWith(prefix + '/'));
    }
    return candidates.includes(n);
  });
}

function buildCustomRoutes(uniRoutes) {
  const routes = {};
  uniRoutes.forEach(route => {
    if (!route || !route.path) return;
    if (matchesAny(OPTIONS.exclude, route.path)) return;
    const short = shortenPath(route.path);
    if (!short) return;
    routes[withLeadingSlash(route.path)] = withLeadingSlash(short);
  });
  Object.assign(routes, OPTIONS.manualRoutes);

  const seen = new Map();
  Object.entries(routes).forEach(([from, to]) => {
    const prev = seen.get(to);
    if (prev && prev !== from) {
      console.warn('[uni-custom-routes] 短路由冲突：「' + from + '」与「' + prev + '」都映射到「' + to + '」');
    } else {
      seen.set(to, from);
    }
  });
  return routes;
}

export function setupCustomRoutes() {
  const uniRoutes = globalThis.__uniRoutes;
  if (!uniRoutes) return;

  const customRoutes = buildCustomRoutes(uniRoutes);
  const redirects = OPTIONS.redirects;

  uniRoutes.forEach(route => {
    if (!route || !route.path) return;
    const short = customRoutes[withLeadingSlash(route.path)];
    if (short) route.path = short;
  });

  // 旧路径过渡兼容：为废弃旧长路径追加纯重定向，透传 query / hash
  Object.keys(redirects).forEach(from => {
    const to = redirects[from];
    if (uniRoutes.some(r => r && r.path && withLeadingSlash(r.path) === from)) return;
    uniRoutes.push({
      path: from,
      redirect: target => ({ path: to, query: target.query, hash: target.hash })
    });
  });

  NAV_APIS.forEach(api => {
    uni.addInterceptor(api, {
      invoke(args) {
        if (!args.url) return;
        // 总是保留业务调用时传入的原始 url，便于后续业务 invoke 按长路径做鉴权 / 埋点
        args.originalUrl = args.url;
        const [path, query] = String(args.url).split('?');
        const target = customRoutes[path] || redirects[path];
        if (target) args.url = query ? target + '?' + query : target;
      }
    });
  });
}
`
}
